name: derry
description: A script manager to help you define script shortcuts and use them effortlessly, and performantly.
version: 1.5.0
repository: https://github.com/frencojobs/derry

environment:
  sdk: ">=2.18.0 <3.0.0"

executables:
  derry:

dependencies:
  args: ^2.3.2
  collection: ^1.17.1
  console: ^4.1.0
  equatable: ^2.0.5
  ffi: ^2.0.1
  mockito: ^5.3.2
  path: ^1.8.3
  string_similarity: ^2.0.0
  tint: ^2.0.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  build_version: ^2.1.1
  lint: ^2.0.1
  test: ^1.22.2

scripts: derry.yaml
